const USER_CLICK = "USER_CLICK";
const GAME_OVER = "GAME_OVER";

const HISTORY_SAVE = "HISTORY_SAVE";
const HISTORY_NEXT = "HISTORY_NEXT";
const HISTORY_PREVIOUS = "HISTORY_PREVIOUS";

const REPLAY = "REPLAY";

const SAVE_SCORE = "SAVE_SCORE";

export {
  USER_CLICK,
  GAME_OVER,
  HISTORY_SAVE,
  HISTORY_NEXT,
  HISTORY_PREVIOUS,
  REPLAY,
  SAVE_SCORE
};
